services:
  app:
    build: .
    container_name: CRM
    ports:
      - "8000:8000"
    depends_on: 
      - db   
    volumes:
      - .:/app
    env_file:
      - .env       
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_HOST=db
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
    command: uvicorn App.main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image : postgres
    
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: